server:
  address: 127.0.0.1
  port: 8080

cassandra:
  cluster:
    - 127.0.0.1
  keyspace: test
  proto_version: 4
  username: test123
  password: test123

mysql:
  database: test
  username: test123
  password: test123