server:
  address: 127.0.0.1
  port: 8080

cassandra:
  cluster:
    - 127.0.0.1
  keyspace: test
  proto_version: 4
  username: test123
  password: test123

redis:
  default: &default
    url: redis://localhost:6379
    db: 1
  
  development:
    <<: *default

  production:
    <<: *default
    url: redis://somehost:6379
